### ISSUE TITLE
delimiter: <class 'pexpect.exceptions.EOF'>

### ISSUE THREAD

**Issue by mike11339** [Tagar/stuff#1]
./keytab.py kafka --domain="QA.LOCAL" --keytab=kafka.keytab --algorithms=arc4-hmac --kvno=1 --debug
{'--algorithms': 'arc4-hmac',
 '--and-test': False,
 '--debug': True,
 '--domain': 'QA.LOCAL',
 '--help': False,
 '--keytab': 'kafka.keytab',
 '--kvno': '1',
 '--update': False,
 '-u': False,
 '<username>': 'kafka',
 'test': False}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pexpect/pty_spawn.py", line 465, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pexpect/spawnbase.py", line 160, in read_nonblocking
    raise EOF('End Of File (EOF). Empty string style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./keytab.py", line 111, in <module>
    wait()
  File "./keytab.py", line 100, in wait
    i = child.expect([prompt, default_prompt], timeout=3)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
<pexpect.pty_spawn.spawn object at 0x10075a128>
command: /usr/sbin/ktutil
args: ['/usr/sbin/ktutil']
buffer (last 100 chars): b''
before (last 100 chars): b'keytab=keytab to operate on keytab\r\n-v, --verbose                                          verbose\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 6041
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b'ktutil:  '")
    1: re.compile("b'ktutil:  '")

**Comment by Tagar** [comment]
Thanks for reporting this issue.

This script wasn't tested with Python3. 

Please check if this works for you using Python2?

**Comment by mike11339** [comment]
Thank you , Tagar for your reply.  I used python 2.7.5 to test, still reports error.

$ ./keytab.py kafka --domain="QA.LOCAL" --keytab="kafka.keytab" --algorithms="arcfour-hmac" --kvno=1
Traceback (most recent call last):
  File "./keytab.py", line 111, in <module>
    wait()
  File "./keytab.py", line 100, in wait
    i = child.expect([prompt, default_prompt], timeout=20)
  File "/Library/Python/2.7/site-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/Library/Python/2.7/site-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/Library/Python/2.7/site-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/Library/Python/2.7/site-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
<pexpect.pty_spawn.spawn object at 0x10c0b1c90>
command: /usr/sbin/ktutil
args: ['/usr/sbin/ktutil']
buffer (last 100 chars): ''
before (last 100 chars): 'keytab=keytab to operate on keytab\r\n-v, --verbose                                          verbose\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 38570
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("ktutil:  ")
    1: re.compile("ktutil:  ")

**Comment by Tagar** [comment]
Which version of ktutil you're using?
Which distribution of Linux and version?

It seems `ktutil` is responding somthing that this script does not expect. 
See http://stackoverflow.com/questions/17879585/eof-when-using-pexpect-and-pxssh

According to http://pexpect.sourceforge.net/doc/ 
> Some UNIX platforms will throw an exception when you try to read from a file descriptor in the EOF state
So it might be that the `ktutil` terminates prematurely, or most likely version of `ktutil` that this script wasn't tested with.

As you can see from your logs above 
> before (last 100 chars): 'keytab=keytab to operate on keytab\r\n-v, --verbose verbose\r\n'

So it seems `ktutil` prints usage. It means arguments passed to `ktutil` aren't understood by the script.
Execute `ktutil` without parameters and post output here.

ps. This script will not work with certain versions of Kerberos - https://github.com/Tagar/stuff/blob/master/keytab.py#L41

**Comment by mike11339** [comment]
You are right, it is ktutil version issue:

ktutil --version
ktutil (Heimdal 1.5.1apple1)
Copyright 1995-2011 Kungliga Tekniska Högskolan
Send bug-reports to heimdal-bugs@h5l.org

Closing the issue now.
